# Generated by Django 4.2.1 on 2023-05-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WatchEvent', 'WatchEvent'), ('PullRequestEvent', 'PullRequestEvent'), ('IssuesEvent', 'IssuesEvent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checker.repository')),
            ],
        ),
    ]
