# Generated by Django 4.2.1 on 2023-05-31 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_repository_events_repository_repo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequestmetrics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pullrequestmetrics',
            name='repository_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='repository_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='checker.repository'),
        ),
        migrations.AlterField(
            model_name='pullrequestmetrics',
            name='respond',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='BasicMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='checker.repository')),
            ],
        ),
        migrations.AddField(
            model_name='pullrequestmetrics',
            name='basicmetrics_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checker.basicmetrics'),
            preserve_default=False,
        ),
    ]
