# Generated by Django 4.2.1 on 2023-05-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_remove_pullrequestmetrics_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicmetrics',
            options={'verbose_name': 'Basic Metric', 'verbose_name_plural': 'Basic Metrics'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='pullrequestmetrics',
            options={'verbose_name': 'Pull Request Metric', 'verbose_name_plural': 'Pull Request Metrics'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='repository_id',
        ),
    ]
